trigger:
- master

strategy:
  matrix:
    windows-nightly:
      imageName: 'windows-latest'
      rustup_toolchain: nightly
    mac-nightly:
      imageName: 'macOS-latest'
      rustup_toolchain: nightly
    linux-nightly:
      imageName: 'ubuntu-latest'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

# https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects
steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all --release --out-dir $(Build.ArtifactStagingDirectory)
    displayName: Cargo build
  - script: cargo test --all --release
    displayName: Cargo test
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'assets'
      publishLocation: 'Container'